language: python
python:
  - "3.6"

install:
  - pip install pandas 
  - pip install numpy
  - pip install matplotlib
  - pip install sklearn

script:
  - python /testsuite/unittests/test_HeatmapCorr.py
  - python /testsuite/unittests/test_HeatmapCorr3.py
  - python /testsuite/unittests/test_addone.py
  - python /testsuite/unittests/test_create_buckets.py
  
