language: python
python:
  - "3.6"

install:
  - pip install pandas 
  - pip install numpy
  - pip install matplotlib

script:
  - python test_HeatmapCorr.py
  - python test_HeatmapCorr3.py
  - python test_addone.py
  - python test_create_buckets.py
  
